package org.fossify.messages.helpers

import android.content.Context
import org.fossify.messages.extensions.getMessagesDB
import org.fossify.messages.models.Reminder
import java.text.SimpleDateFormat
import java.util.*
import java.util.regex.Pattern

object ReminderHelper {
    private val ksrtcPattern = Pattern.compile("KSRTC m-Ticket from: (.*) to: (.*) PsngrName:.*PNR No: ([A-Z0-9]*) JnyDate: (\\d{1,2} [A-Za-z]*) DepTime: (\\d{2}:\\d{2})", Pattern.CASE_INSENSITIVE)
    private val ksrtcDirectPattern = Pattern.compile("KSRTC Bus PNR:([A-Z0-9]*), DOJ:(\\d{2}-[A-Za-z]{3}-\\d{4}) at (\\d{2}:\\d{2})", Pattern.CASE_INSENSITIVE)
    private val irctcPattern = Pattern.compile("PNR:(\\d{10}),TRN:(\\d{5}),DOJ:(\\d{2}-\\d{2}-\\d{2}),.*DP:(\\d{2}:\\d{2})", Pattern.CASE_INSENSITIVE)
    private val billPattern = Pattern.compile("bill.*due.*(\\d{1,2}[-/]\\d{1,2}[-/]\\d{2,4})", Pattern.CASE_INSENSITIVE)
    private val moviePattern = Pattern.compile("ticket.*showtime.*(\\d{2}:\\d{2}).*on (\\d{1,2} [A-Za-z]*)", Pattern.CASE_INSENSITIVE)

    fun parseAndSaveReminder(context: Context, body: String, smsId: Long, threadId: Long) {
        val reminders = mutableListOf<Reminder>()

        // KSRTC m-Ticket
        val ksrtcMatcher = ksrtcPattern.matcher(body)
        if (ksrtcMatcher.find()) {
            val from = ksrtcMatcher.group(1) ?: ""
            val to = ksrtcMatcher.group(2) ?: ""
            val pnr = ksrtcMatcher.group(3) ?: ""
            val jnyDateStr = ksrtcMatcher.group(4) ?: ""
            val depTimeStr = ksrtcMatcher.group(5) ?: ""
            
            val dueDate = parseDate(jnyDateStr, depTimeStr, "dd MMMM HH:mm")
            if (dueDate != null) {
                reminders.add(Reminder(
                    title = "KSRTC Bus: $from to $to (PNR: $pnr)",
                    dueDate = dueDate,
                    smsId = smsId,
                    smsThreadId = threadId,
                    isAutoGenerated = true
                ))
            }
        }

        // KSRTC Bus PNR
        val ksrtcDirectMatcher = ksrtcDirectPattern.matcher(body)
        if (ksrtcDirectMatcher.find()) {
            val pnr = ksrtcDirectMatcher.group(1) ?: ""
            val dojStr = ksrtcDirectMatcher.group(2) ?: ""
            val timeStr = ksrtcDirectMatcher.group(3) ?: ""
            
            val dueDate = parseDate("$dojStr $timeStr", "dd-MMM-yyyy HH:mm")
            if (dueDate != null) {
                reminders.add(Reminder(
                    title = "KSRTC Bus (PNR: $pnr)",
                    dueDate = dueDate,
                    smsId = smsId,
                    smsThreadId = threadId,
                    isAutoGenerated = true
                ))
            }
        }

        // IRCTC
        val irctcMatcher = irctcPattern.matcher(body)
        if (irctcMatcher.find()) {
            val pnr = irctcMatcher.group(1) ?: ""
            val dojStr = irctcMatcher.group(3) ?: ""
            val dpTimeStr = irctcMatcher.group(4) ?: ""
            
            val dueDate = parseDate("$dojStr $dpTimeStr", "dd-MM-yy HH:mm")
            if (dueDate != null) {
                reminders.add(Reminder(
                    title = "Train Journey (PNR: $pnr)",
                    dueDate = dueDate,
                    smsId = smsId,
                    smsThreadId = threadId,
                    isAutoGenerated = true
                ))
            }
        }

        // Bill
        val billMatcher = billPattern.matcher(body)
        if (billMatcher.find()) {
            val dateStr = billMatcher.group(1) ?: ""
            val format = if (dateStr.contains("-")) {
                if (dateStr.length > 8) "dd-MM-yyyy" else "dd-MM-yy"
            } else {
                if (dateStr.length > 8) "dd/MM/yyyy" else "dd/MM/yy"
            }
            val dueDate = parseDate(dateStr, format)
            if (dueDate != null) {
                reminders.add(Reminder(
                    title = "Bill Payment Due",
                    dueDate = dueDate,
                    smsId = smsId,
                    smsThreadId = threadId,
                    isAutoGenerated = true
                ))
            }
        }

        // Movie
        val movieMatcher = moviePattern.matcher(body)
        if (movieMatcher.find()) {
            val timeStr = movieMatcher.group(1) ?: ""
            val dateStr = movieMatcher.group(2) ?: ""
            val dueDate = parseDate(dateStr, timeStr, "dd MMMM HH:mm")
            if (dueDate != null) {
                reminders.add(Reminder(
                    title = "Movie Show",
                    dueDate = dueDate,
                    smsId = smsId,
                    smsThreadId = threadId,
                    isAutoGenerated = true
                ))
            }
        }

        reminders.forEach {
            context.getMessagesDB().RemindersDao().insert(it)
        }
    }

    private fun parseDate(dateStr: String, timeStr: String, format: String): Long? {
        return try {
            val fullStr = if (format.contains("HH:mm") && !dateStr.contains(":")) "$dateStr $timeStr" else dateStr
            val sdf = SimpleDateFormat(format, Locale.ENGLISH)
            val date = sdf.parse(fullStr)
            
            // If year is missing (e.g. "14 December"), assume current year or next year if date passed
            if (!format.contains("y")) {
                val cal = Calendar.getInstance()
                val currentYear = cal.get(Calendar.YEAR)
                cal.time = date!!
                cal.set(Calendar.YEAR, currentYear)
                if (cal.timeInMillis < System.currentTimeMillis() - 1000L * 60 * 60 * 24 * 30) { // more than 30 days in past
                    cal.add(Calendar.YEAR, 1)
                }
                cal.timeInMillis
            } else {
                date?.time
            }
        } catch (e: Exception) {
            null
        }
    }

    private fun parseDate(fullStr: String, format: String): Long? {
        return try {
            val sdf = SimpleDateFormat(format, Locale.ENGLISH)
            sdf.parse(fullStr)?.time
        } catch (e: Exception) {
            null
        }
    }
}
