package org.fossify.messages.models

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "reminders")
data class Reminder(
    @PrimaryKey(autoGenerate = true) val id: Long? = null,
    @ColumnInfo(name = "title") val title: String,
    @ColumnInfo(name = "due_date") val dueDate: Long,
    @ColumnInfo(name = "sms_id") val smsId: Long? = null,
    @ColumnInfo(name = "sms_thread_id") val smsThreadId: Long? = null,
    @ColumnInfo(name = "is_auto_generated") val isAutoGenerated: Boolean = false,
    @ColumnInfo(name = "creation_date") val creationDate: Long = System.currentTimeMillis(),
    @ColumnInfo(name = "is_completed") val isCompleted: Boolean = false
)
